package com.ipl2019;

public class SortingEnums {
    public enum StatisticFields {
        BATTING_AVERAGE, BATSMAN_STRIKING_RATE, MAX_SIX_AND_FOUR, BEST_STRIKING_RATE_WITH_SIX_AND_FOUR,
        BEST_AVG_WITH_BEST_STRIKING, MAX_RUN_WITH_BEST_AVG,BOWLING_AVERAGE,BOWLER_STRIKING_RATE,BOWLER_BEST_ECONOMY,
        BEST_STRIKING_RATE_WITH_4W_AND_5W, BEST_BOWLING_AVERAGE_WITH_STRIKING_RATE,MAX_WICKETS_With_BEST_AVG;
    }
}
